# Generated by Django 5.2.7 on 2025-10-11 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('mobile', models.CharField(blank=True, max_length=30)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('summary', models.TextField(blank=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills or short list')),
                ('education', models.TextField(blank=True, help_text='Add education entries (one per line)')),
                ('projects', models.TextField(blank=True, help_text='Add project entries (one per line)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
